packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@tailwindcss/oxide': true
  workerd: true
  sharp: true
  esbuild: true

minimumReleaseAgeExclude:
  - 'expo'
  - '@expo/*'
  - 'expo-*'
  - 'babel-preset-expo'
